
import { Song, MoodType, Reaction } from './types';

export const MOODS: MoodType[] = ['Euphoric', 'Melancholy', 'Aggressive', 'Dreamy', 'Raw', 'Vibe'];

export const GENRES = ['All Genres', 'Rap', 'Lo-fi', 'Soul', 'Pop', 'Rock', 'Synthwave', 'Folk', 'Experimental', 'Phonk'];

export const LANGUAGES = ['All Languages', 'Hindi', 'English', 'Punjabi', 'Bengali', 'Tamil', 'Spanish'];

export const COUNTRIES = ['All Countries', 'India', 'USA', 'Germany', 'Canada', 'UK', 'Japan'];

export const INDIAN_STATES = ['All States', 'Maharashtra', 'Delhi', 'Punjab', 'West Bengal', 'Karnataka', 'Tamil Nadu', 'Kerala', 'Rajasthan', 'Gujarat', 'Uttar Pradesh', 'Bihar', 'Assam'];

export const REACTIONS: Reaction[] = [
  { emoji: '❤️', label: 'Love' },
  { emoji: '😔', label: 'Deep' },
  { emoji: '🌙', label: 'Late Night' },
  { emoji: '💭', label: 'Thinking' },
  { emoji: '🔥', label: 'Fire' }
];

export const MOCK_SONGS: Song[] = [
  {
    id: '1',
    title: 'Starboy',
    artist: 'The Weeknd',
    cover: 'https://upload.wikimedia.org/wikipedia/en/3/39/The_Weeknd_-_Starboy.png',
    youtubeId: '34Na4j8AVgA',
    mood: 'Vibe',
    year: 2016,
    genre: 'Pop',
    language: 'English',
    country: 'USA',
    isUnderground: false,
    duration: 230,
    likes: 8500000,
    reactions: { '🔥': 50000, '🌙': 12000 },
    songType: 'Official',
    targetListener: 'Late night drivers'
  },
  {
    id: '2',
    title: '3:59 AM',
    artist: 'DIVINE',
    cover: 'https://c.saavncdn.com/973/3-59-AM-Hindi-2021-20210716024929-500x500.jpg',
    youtubeId: 'sK7Ri7xW_N8',
    mood: 'Raw',
    year: 2021,
    genre: 'Rap',
    language: 'Hindi',
    country: 'India',
    state: 'Maharashtra',
    isUnderground: true,
    duration: 245,
    likes: 950000,
    reactions: { '🔥': 80000, 'Raw': 5000 },
    songType: 'Official'
  },
  {
    id: '3',
    title: 'After Dark',
    artist: 'Mr. Kitty',
    cover: 'https://i1.sndcdn.com/artworks-000216578021-82d2n1-t500x500.jpg',
    youtubeId: 'waAlgFq9Xq8',
    mood: 'Dreamy',
    year: 2014,
    genre: 'Synthwave',
    language: 'English',
    country: 'USA',
    isUnderground: true,
    duration: 259,
    likes: 1200000,
    reactions: { '🌙': 45000, '💭': 20000 },
    songType: 'Official'
  },
  {
    id: '4',
    title: 'Glimpse of Us',
    artist: 'Joji',
    cover: 'https://upload.wikimedia.org/wikipedia/en/2/23/Joji_-_Glimpse_of_Us.png',
    youtubeId: 'FvOpPeKSf_4',
    mood: 'Melancholy',
    year: 2022,
    genre: 'Lo-fi',
    language: 'English',
    country: 'Japan',
    isUnderground: true,
    duration: 233,
    likes: 2100000,
    reactions: { '😔': 150000, '🌙': 40000 }
  },
  {
    id: '5',
    title: 'Brown Munde',
    artist: 'AP Dhillon',
    cover: 'https://c.saavncdn.com/959/Brown-Munde-Punjabi-2020-20200918074040-500x500.jpg',
    youtubeId: 'VNs_cCtdbPc',
    mood: 'Aggressive',
    year: 2020,
    genre: 'Rap',
    language: 'Punjabi',
    country: 'Canada',
    isUnderground: true,
    duration: 240,
    likes: 6400000,
    reactions: { '🔥': 200000 }
  },
  {
    id: '6',
    title: 'Chaleya',
    artist: 'Arijit Singh',
    cover: 'https://c.saavncdn.com/026/Chaleya-From-Jawan-Hindi-2023-20230814143419-500x500.jpg',
    youtubeId: 'VAdGW7QDJiU',
    mood: 'Euphoric',
    year: 2023,
    genre: 'Pop',
    language: 'Hindi',
    country: 'India',
    state: 'Maharashtra',
    isUnderground: false,
    duration: 188,
    likes: 2300000,
    reactions: { '❤️': 55000 },
    songType: 'Official'
  },
  {
    id: '7',
    title: 'Lover',
    artist: 'Diljit Dosanjh',
    cover: 'https://c.saavncdn.com/397/MoonChild-Era-Punjabi-2021-20210822055653-500x500.jpg',
    youtubeId: 'mHj_bI9gTGU',
    mood: 'Vibe',
    year: 2021,
    genre: 'Pop',
    language: 'Punjabi',
    country: 'India',
    state: 'Punjab',
    isUnderground: false,
    duration: 210,
    likes: 1800000,
    reactions: { '🔥': 40000 },
    songType: 'Official'
  },
  {
    id: '8',
    title: 'Apna Bana Le',
    artist: 'Arijit Singh',
    cover: 'https://c.saavncdn.com/815/Bhediya-Hindi-2022-20221206114639-500x500.jpg',
    youtubeId: 'ElZfdU54Cp8',
    mood: 'Melancholy',
    year: 2022,
    genre: 'Pop',
    language: 'Hindi',
    country: 'India',
    state: 'Maharashtra',
    isUnderground: false,
    duration: 245,
    likes: 3100000,
    reactions: { '❤️': 60000, '😔': 12000 },
    songType: 'Official'
  },
  {
    id: '9',
    title: 'Metamorphosis',
    artist: 'Interworld',
    cover: 'https://i.scdn.co/image/ab67616d0000b273574c35e97151121d4c26a576',
    youtubeId: 'Cnppq12j7VI',
    mood: 'Aggressive',
    year: 2022,
    genre: 'Phonk',
    language: 'English',
    country: 'USA',
    isUnderground: true,
    duration: 142,
    likes: 5000000,
    reactions: { '🔥': 85000 },
    songType: 'Official'
  },
  {
    id: '10',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    cover: 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    youtubeId: '4NRXx6U8ABQ',
    mood: 'Euphoric',
    year: 2020,
    genre: 'Pop',
    language: 'English',
    country: 'USA',
    isUnderground: false,
    duration: 200,
    likes: 4500000,
    reactions: { '❤️': 25000 },
    songType: 'Official'
  },
  {
    id: '11',
    title: 'Kho Gaye',
    artist: 'Taaruk Raina',
    cover: 'https://c.saavncdn.com/492/Mismatched-Season-2-Soundtrack-From-the-Netflix-Series-Hindi-2022-20221012192736-500x500.jpg',
    youtubeId: '8q2oYd9s09E',
    mood: 'Melancholy',
    year: 2022,
    genre: 'Pop',
    language: 'Hindi',
    country: 'India',
    state: 'Maharashtra',
    isUnderground: true,
    duration: 185,
    likes: 340000,
    reactions: { '😔': 20000 },
    songType: 'Official'
  },
  {
    id: '12',
    title: 'Way Down We Go',
    artist: 'Kaleo',
    cover: 'https://upload.wikimedia.org/wikipedia/en/2/23/Way_Down_We_Go.jpg',
    youtubeId: '0-7IHOXkiV8',
    mood: 'Raw',
    year: 2016,
    genre: 'Rock',
    language: 'English',
    country: 'Iceland',
    isUnderground: false,
    duration: 213,
    likes: 4200000,
    reactions: { '🔥': 60000 },
    songType: 'Official'
  }
];
